services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-challenge-api
    environment:
      LOG_LEVEL: INFO
      ENABLE_PROMETHEUS_METRICS: "true"
    ports:
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: tech-challenge-prometheus
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.2.0
    container_name: tech-challenge-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ops/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./ops/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  grafana_data:

networks:
  monitoring:
    driver: bridge
