{
 "title": "Tech Challenge API Observability",
 "tags": [
  "api",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total HTTP Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_http_request_errors_total)"
    }
   ]
  },
  {
   "title": "HTTP Latency p95 by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_request_duration_seconds_bucket[5m])) by (le, route))",
     "legendFormat": "{{route}} p95"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "app_system_cpu_percent", "legendFormat": "CPU" },
    { "expr": "app_system_memory_percent", "legendFormat": "Memory" }
   ]
  }
 ]
}